// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const { config } = require("dotenv");
const { defineConfig } = require("prisma/config");

config({ override: true });

if (!process.env["DATABASE_URL"]) {
  throw new Error("DATABASE_URL is not defined");
}

module.exports = defineConfig({
  schema: "packages/database/prisma/schema.prisma",
  migrations: {
    path: "packages/database/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
